Update my_manual_workflow.yml

diff --git a/.github/workflows/my_manual_workflow.yml b/.github/workflows/my_manual_workflow.yml
--- a/.github/workflows/my_manual_workflow.yml
+++ b/.github/workflows/my_manual_workflow.yml
@@ -1,21 +1,55 @@
-name: Manually triggered workflow
-on:
-  workflow_dispatch:
-    inputs:
-      name:
-        description: 'Person to greet'
-        required: true
-        default: 'Mona the Octocat'
-      home:
-        description: 'location'
-        required: false
-        default: 'The Octoverse'
+name: "When a jobs is skipped, what do the job status check functions do?"
+
+on: push
 
 jobs:
-  say_hello:
+
+  always-fails:
     runs-on: ubuntu-latest
     steps:
-    - run: |
-        echo "Hello ${{ github.event.inputs.name }}!"
-        echo "- in ${{ github.event.inputs.home }}!"
-    - run: echo "The runner name is ${{ runner.name }} the env variables is OS $RUNNER_OS and name $RUNNER_NAME"
+      - shell: bash
+        run: exit 1
+
+  always-skipped:
+    runs-on: ubuntu-latest
+    needs:
+      - always-fails 
+    if: false
+    steps:
+      - shell: bash
+        run: echo "This job will always be skipped"
+
+  runs-upon-success:
+    runs-on: ubuntu-latest
+    needs:
+      - always-skipped
+    if: success()
+    steps:
+      - shell: bash
+        run: echo "This job should run when no job has failed or been cancelled"
+  runs-upon-no-failure:
+    runs-on: ubuntu-latest
+    needs:
+      - always-skipped
+    if: "!(failure() || cancelled())"
+    steps:
+      - shell: bash
+        run: echo "This job should run when no job has failed or been cancelled"
+  runs-upon-cancellation:
+    runs-on: ubuntu-latest
+    needs:
+      - always-skipped
+    if: cancelled()
+    steps:
+      - shell: bash
+        run: echo "This job should run when the workflow has been cancelled"
+  runs-upon-failure:
+    runs-on: ubuntu-latest
+    needs:
+      - always-skipped
+    if: failure()
+    steps:
+      - shell: bash
+        run: echo "This job should run when any of the previous jobs have failed"
+        
+  
