fail job

diff --git a/.github/workflows/my_workflow.yml b/.github/workflows/my_workflow.yml
--- a/.github/workflows/my_workflow.yml
+++ b/.github/workflows/my_workflow.yml
@@ -9,7 +9,7 @@ jobs:
     steps:
       # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
       - name: step 1
-        run: echo "this might fail!"
+        run: echo "this might fail!" && exit 1
       - name: step 2
         run: echo "this should work!"
       - name: step 3 - success
